export const types = [
    { id: 0, value: "", text: "--Please choose a type--" },
    { id: 1, value: "normal", text: "normal" },
    { id: 2, value: "fire", text: "fire" },
    { id: 3, value: "water", text: "water" },
    { id: 4, value: "electric", text: "electric" },
    { id: 5, value: "grass", text: "grass" },
    { id: 6, value: "ice", text: "ice" },
    { id: 7, value: "fighting", text: "fighting" },
    { id: 8, value: "poison", text: "poison" },
    { id: 9, value: "ground", text: "ground" },
    { id: 10, value: "flying", text: "flying" },
    { id: 11, value: "psychic", text: "psychic" },
    { id: 12, value: "bug", text: "bug" },
    { id: 13, value: "rock", text: "rock" },
    { id: 14, value: "ghost", text: "ghost" },
    { id: 15, value: "dragon", text: "dragon" },
    { id: 16, value: "dark", text: "dark" },
    { id: 17, value: "steel", text: "steel" },
    { id: 18, value: "fairy", text: "fairy" }
];